### ISSUE TITLE
Drop the usage of the node crypto module for `http-signature-utils`

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/open-payments#416]
## Context
Currently, using the SDK outside of a Node environment is impractical, primarily due to the use on Node's crypto module for generating key pairs using the Ed25519 algorithm. The [SubtleCrypto API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto), while accessible in both browser and Node (v18 or earlier - with polyfill, v20 or later - without polyfill) environments, does not yet offer support for Ed25519 or is experimental:

- In Chromium-based browsers, the algorithm is accessible by activating the `Experimental Web Platform Features` flag ([implementation status](https://github.com/WICG/webcrypto-secure-curves/issues/20));
- Firefox does not support the algorithm;
- In Node, the Ed25519 algorithm is still considered [experimental](https://nodejs.org/dist/latest-v20.x/docs/api/webcrypto.html#ed25519ed448x25519x448-key-pairs);
  
## Todos
- [ ] Update Node version to 20 (with backwards compatibility)
- [ ] Use `@noble/ed25519` to generate the key pair;
- [ ] Take advantage of an ASN.1 decoder to validate the algorithm of a private key when loading it;
- [ ] Update `http-message-signatures` to it's latest version (using 0.1.2 - latest 1.0.4);
- [ ] Make sure that importing private keys that were generated with the Node crypto module or other libraries work as well;
