### ISSUE TITLE
Make `interact_ref` optional on POST `/continue/{id}`

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/open-payments#433]
## Context
The `interact_ref` is not actually required in the body of continuation requests. In the case of a grant request with no `interact.finish` method, we should be able to poll the continuation endpoint without an `interact_ref`. But it's still required by the schema/client.

## Todos
- [ ] Update spec to make interact_ref optional on POST `/continue/{id}`
- [ ] Ensure client can make continuation requests without an `interact_ref`
- [ ] update bruno collection to use this method and update the docs https://github.com/interledger/rafiki/pull/2507#discussion_r1516135752
